### ISSUE TITLE
Bad syntax in css

### ISSUE THREAD

**Issue by ipepe** [NUKnightLab/TimelineJS3#297]
I guess ```padding:right:2px``` isnt a good syntax in css:
```css
tl-timeaxis-tick-text{opacity:0;white-space:normal;padding-left:2px;padding:right:2px}.tl-timeaxis
```
