### ISSUE TITLE
Support using a "Tags" column

### ISSUE THREAD

**Issue by mccrodp** [NUKnightLab/TimelineJS3#556]
Again, awesome library / app guys, I appreciated the work. We have a PoC of an app working now using it as a [Availability Forecasting tool](https://mccrodp.github.io/availability-forecast/) tool.

I'd love to be able to add some kind of "Tags" column to the spreadsheet / JSON data parsing. For example if Derek (the Heading in this row of spreadsheet) had `php` and `js` tags in this CSV "Tags" column, then the classes `.js` and `.php` would be new selectors useable in the CSS and we can add the below for example, to add indicators to the beside the Heading row text ("Derek H")

````css
.js, .php {
        border-radius: 50%;
	width: 30px;
	height: 30px;
}
.js {
        color: red;
}
.php {
        color: blue;
}
````

...and then we get something like this mockup, modified from the linked example above.

<img width="1220" alt="available-forecast" src="https://user-images.githubusercontent.com/559938/32033543-fef178d8-ba47-11e7-9859-d323427a970b.png">

Is this something you think could be useful in the main repo here, or just in my own forked repo? Any advice on accomplishing a result similar to this either way is appreciated.
