### ISSUE TITLE
CSS word-break does not work in Firefox

### ISSUE THREAD

**Issue by Aybee** [NUKnightLab/TimelineJS3#597]
On the options page https://timeline.knightlab.com/docs/options.html you use CSS word-break to break long words in `<code>`.
```css
code {
  word-break: break-all;
}
```
For Firefox you have to add
```css
code {
  word-wrap: break-word;
}
```
